language: python
python:
- 3.8
- 3.7
- 3.6
addons:
  apt:
    update: true
    packages:
    - unixodbc
    - odbcinst
    - unixodbc-dev
    - libz-dev
before_install: openssl aes-256-cbc -K $encrypted_268b49090a6d_key -iv $encrypted_268b49090a6d_iv
  -in resources/ibm-iaccess-1.1.0.13-1.0.amd64.deb.enc -out resources/ibm-iaccess-1.1.0.13-1.0.amd64.deb
  -d
install:
- pip install -U tox-travis
- sudo dpkg -i resources/ibm-iaccess-1.1.0.13-1.0.amd64.deb
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: giBHhKcJ4a3X/L7gq0ObDkhh6PeEUe1YK7kQziayRFb8daUEG5pipSwUrdRo58ELXiT/m2svLYGTDxG9HhLvnoGqSgcpAjS0GNFWTbqrIaQDSnWi51Uz2XeK+daOw6tVOjaZ3q9MniRJNpLWgikZ4TKppdynYcyIMeZD4x0oUXBUc3OQfFj1nawWMUvD1w0unTDwAeg2dMpc0+g+zrSQ+SOfW6YHegqX0MAFkCO5+KCB39vypHQ2VT/6f8ne96hlOwGdVQr8v2NqCPud+9viT268hUnQzLhbesDCQ1RgKKEWIygoXMHNruhoeDhs879J2RlZwHk73T9JUig2wzElrfwFE+UBxVMJLRMDLwKO6ENuAgxZqv+1mfinpjr44Sx7bLc4niLM459buQZkJBgv4KWy8zNvsJjWepVAvrcQ22XKqm2WlNYDNUCNTKZtNJcVLQqQvssV1bSPjHKNuAP7nenGZSDTBY7YB/YteDZpuU8ygbKFNoNAvBpxZrViuUkUSo1Vq+0Reir3ecfk/OSDXiqVLSGLa+o2RU2h6BggYTaMKArCVkFg2hhDzcCPSnA4amPPDmZiv5Uk6ynydkmdMlKKNCPrGIz2LYvrebHkaVx0vcx41st8MXqxyDHYq7wPaddFxCbZoSRtRrGI1CBBvT8ih/d2TnKZHvh8iHTfSl0=
  on:
    tags: true
    repo: soundstripe/iaccess
    python: 3.8
env:
  global:
  - IACCESS_HOST=pub400.com
  - secure: Gha750o6/nR6eCqtH36KjoiGn3pm7tZ+lj74UpO6MQp8V8smAVWiJqTXFWwhlQsLLEs3z/ItyAG2A259d7tzWeUq4Gn+6u2QUwUu4Gy7xxyA/0d2JGMTY8lhaT5FsoJdq72NX5o0URuyae0yHUFLdctHg02HkWrnBKJlKKsBu6xFlzhxJTthsxErJsgLEaZseKmdhaf42TICAqCIgtXf2KyVLjBVLtEYG1J7FyC+1hivkCZMxZL+l6IcqD534RsWc7gB6zvYMI8MSX7b75wUHvV87IMaAVNAFgyYFPMKtws6pPxSkMIt+CuHpVk0M8inmWe1LzwNJgH4WDvfejlkJbgI5/HUH1NeV6xSCHYsk1iUtkKxTIQFGABqP1NMCam4rzrmc3xmJGRNNqt7/MfQ9Xts+kbsTlvZIX4qH+1q/ceIi5hS76O9Ew+bmXGBhVi6ExwXvmTv/MauspGJtpYji5iWfiNQ8EsSePKDnnbSjUFy+/xeJAjLb3BzmzD/ybi+VIBTglcf6MQNyHbrYQ/L5rydLzdq6OGM81IfCECzCtoxaOILWwWqqmQk8//c5jYYvdt560Z/AmF/snPHlE9MaFyKK5oB3Z3/C8EIfLqH9uGQx+qP0odaaf1Z+qmxaqBkF36RFxYZiFQWR1Dult5NiYNhpl2wt7azB1ojemcfeKE=
  - secure: G8LhNVUmvrYwoWXESlFSwRkyJRU5b8VWFr/GGUApA7R6yof2knymINyOwBgNqnlgrCUnzcpi0SjqgIVYlR0tfhkia372OBE+LLOntYC93b2/1+cdos5EqQ+cUNGxwfbTBIMQ10M+BiVK+Reuo6IZ8iQ8FusMewNIRgcbY1VJMCNZm6m1FhKKds0Pw9zHS2Ue8dHgMSPlwRMEE0tAn07cdBhv1yi4mmMBnq9tGsdWtmvGqPnqolz7cF6c5vYmvIURCjsLM2F2WAcRxJI3+nV9zL04/YZM4KOUdokN5RUu8fp3OIWY+ABxWrne2nln/L4MEejkiGoJy5u3wD1apZ0U+9SUSdjFYbUibiYK25d5/9JjkgG1cSs2hOqZCJiZTBznrSlKnqKNOAj1lrVxOOs0l40rRNAnZrvQqPiMBFgeqk5Wp1qIT9S/geiqttY4kRpIdVZksScYdoHKG4fyMGSPPdRSJqIvXdaIVt4Xnx9byf5vkOFsWTz1TWKt6GSf20G5hyDDd7cgCNyc6Yk/zrIhgyKg2B5aNqO+MTGs3DWbNsZSH+FuBj0A0BLb1lfRMp30FYRenR5cVP+XGTLgg7KQJaC/Ly8k2/80KBCBUIR39M9B34y9bs25nDTniUW1L7pNwHL2oWol4/Gpuj495S7Lzip0B92xEoEWtxzE7bPnmdg=
  - secure: HwpaHfVitUUwzXOLE2Uif/1vGgfw7Ys2fMQnOUAYzLfL8hC64BV9fIvbRYXUXEhDZTySbgBYoUY9yWpDOw/zS6yB2Cxjd9+7t7OTxNvdQENBD2tYUBUhi14A35YqZz/9QPMhTtbfCm6k39syjC85HfRJ1LfM1xcK8WJWyXgz2Y1ijj2cgmX8FLyXoz1Evz5nih38M6ZokM8qi4euPYcylK4N9K2vAc0Q1K6u8Wxp3IGlaZWN87k1n7Wbvdi195qLxg4besty5Dhro2392ExI6vVHgaXZbnDpRSttYPt5QsVyyD9sZryBO2cTyZgrCvQj+5Sa6JehBAO736j5pZhbBrFKyQegso1v2CH1EWFy2DaNUi0Nvd7gBUadI+QWFlYxVN4+XPKrrImWUv6UraB9e0LoPrH7d/OeZeDXwFgen0LfjUmkakHF/3150tbrxG/E2upJ7nLQnh63ozE3LwEng6bWxB8VI5h4SbDQEijTq6cHHH9agDcdDrSSHMfDINeH9Pcj9sOdE52EjSgYd0DTGljMEhLTPMshGrXt/sB5mKR0/ydG9vg59AKsHwqU/RIgP8ru/3oZZj1Ur/Kmdzh1/agHbKuFF7s1iSeQ9QEKnjVRfP7j4flmswcVIGFTnI5mWHry6O45Ydw4K8oYRjX4j1fkqE7arBql9f5GMPqS/xw=
  - secure: xP+k2/DR7c3XTn9VJwkpoUKDY7nLE1hxT8X0eAtykTkSd1Fg/qY83/UlRuqZ4TNasYwdirT672GAF3B/O6TPKn8bL1ehoBT69YU1BeGBRlECT8RNJi3dPzDEFFV85leXLkrjQZvg2WG7X/npQ5KCeC4GaNcb3pgjYB09CEU35vAcTTxSo5ZFxNaoUEAxq4DCx/lzkiqslU4q9bmzjDYaYxhzI2TBKIRdDpPZpxVPLr52mRKcH0UdwXeafLaj8TOA9hW641RmWd0gi+JTmaOPflMkdd/uXGBLCJevDJnal40RHB12sZidSIIIlgVvKGxYKS5pK7SrBW5AK6ndhxz1xugOs31waULBG4jCpNqAJgYqVzqd/bP/iT13apvYbyPFL8cyBy3mERLQF7m7dCdN0pJrY3eCJv4JWx4fRfXmD90DJ2hGCSfx60KDEWZxoQNsz21k14urXWm2J5on2uAii36GGBloUVPuLMGp/A0060HeYtXTY6A/DAns0g1IcOSmYXJmoFAPklCQMuukAq6yxvdsTcRAkFQQfhGNGISXHEd0fxAQucDLJaB9+lf4++O8sGujlfxvCNDz9B61JPIQ6Dsrcc9ZFyjTPPH9suTzXJ9JzaQ8rE34kwHOwR/tu8YgsBzbXfBaf1yRwYfKnlb2gnskAjLDmQEPq3GJ8Dtydrg=
