language: python
python:
- 3.8
- 3.7
- 3.6
addons:
  apt:
    update: true
    packages:
    - unixodbc
    - odbcinst
    - unixodbc-dev
    - libz-dev
before_install: openssl aes-256-cbc -K $encrypted_268b49090a6d_key -iv $encrypted_268b49090a6d_iv
  -in resources/ibm-iaccess-1.1.0.13-1.0.amd64.deb.enc -out resources/ibm-iaccess-1.1.0.13-1.0.amd64.deb
  -d
install:
- pip install -U tox-travis
- sudo dpkg -i resources/ibm-iaccess-1.1.0.13-1.0.amd64.deb
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: "[PYPI_API_KEY]"
  on:
    tags: true
    repo: soundstripe/iaccess
    python: 3.8
env:
  global:
  - IACCESS_HOST=pub400.com
  - secure: Gha750o6/nR6eCqtH36KjoiGn3pm7tZ+lj74UpO6MQp8V8smAVWiJqTXFWwhlQsLLEs3z/ItyAG2A259d7tzWeUq4Gn+6u2QUwUu4Gy7xxyA/0d2JGMTY8lhaT5FsoJdq72NX5o0URuyae0yHUFLdctHg02HkWrnBKJlKKsBu6xFlzhxJTthsxErJsgLEaZseKmdhaf42TICAqCIgtXf2KyVLjBVLtEYG1J7FyC+1hivkCZMxZL+l6IcqD534RsWc7gB6zvYMI8MSX7b75wUHvV87IMaAVNAFgyYFPMKtws6pPxSkMIt+CuHpVk0M8inmWe1LzwNJgH4WDvfejlkJbgI5/HUH1NeV6xSCHYsk1iUtkKxTIQFGABqP1NMCam4rzrmc3xmJGRNNqt7/MfQ9Xts+kbsTlvZIX4qH+1q/ceIi5hS76O9Ew+bmXGBhVi6ExwXvmTv/MauspGJtpYji5iWfiNQ8EsSePKDnnbSjUFy+/xeJAjLb3BzmzD/ybi+VIBTglcf6MQNyHbrYQ/L5rydLzdq6OGM81IfCECzCtoxaOILWwWqqmQk8//c5jYYvdt560Z/AmF/snPHlE9MaFyKK5oB3Z3/C8EIfLqH9uGQx+qP0odaaf1Z+qmxaqBkF36RFxYZiFQWR1Dult5NiYNhpl2wt7azB1ojemcfeKE=
  - secure: G8LhNVUmvrYwoWXESlFSwRkyJRU5b8VWFr/GGUApA7R6yof2knymINyOwBgNqnlgrCUnzcpi0SjqgIVYlR0tfhkia372OBE+LLOntYC93b2/1+cdos5EqQ+cUNGxwfbTBIMQ10M+BiVK+Reuo6IZ8iQ8FusMewNIRgcbY1VJMCNZm6m1FhKKds0Pw9zHS2Ue8dHgMSPlwRMEE0tAn07cdBhv1yi4mmMBnq9tGsdWtmvGqPnqolz7cF6c5vYmvIURCjsLM2F2WAcRxJI3+nV9zL04/YZM4KOUdokN5RUu8fp3OIWY+ABxWrne2nln/L4MEejkiGoJy5u3wD1apZ0U+9SUSdjFYbUibiYK25d5/9JjkgG1cSs2hOqZCJiZTBznrSlKnqKNOAj1lrVxOOs0l40rRNAnZrvQqPiMBFgeqk5Wp1qIT9S/geiqttY4kRpIdVZksScYdoHKG4fyMGSPPdRSJqIvXdaIVt4Xnx9byf5vkOFsWTz1TWKt6GSf20G5hyDDd7cgCNyc6Yk/zrIhgyKg2B5aNqO+MTGs3DWbNsZSH+FuBj0A0BLb1lfRMp30FYRenR5cVP+XGTLgg7KQJaC/Ly8k2/80KBCBUIR39M9B34y9bs25nDTniUW1L7pNwHL2oWol4/Gpuj495S7Lzip0B92xEoEWtxzE7bPnmdg=
  - secure: HwpaHfVitUUwzXOLE2Uif/1vGgfw7Ys2fMQnOUAYzLfL8hC64BV9fIvbRYXUXEhDZTySbgBYoUY9yWpDOw/zS6yB2Cxjd9+7t7OTxNvdQENBD2tYUBUhi14A35YqZz/9QPMhTtbfCm6k39syjC85HfRJ1LfM1xcK8WJWyXgz2Y1ijj2cgmX8FLyXoz1Evz5nih38M6ZokM8qi4euPYcylK4N9K2vAc0Q1K6u8Wxp3IGlaZWN87k1n7Wbvdi195qLxg4besty5Dhro2392ExI6vVHgaXZbnDpRSttYPt5QsVyyD9sZryBO2cTyZgrCvQj+5Sa6JehBAO736j5pZhbBrFKyQegso1v2CH1EWFy2DaNUi0Nvd7gBUadI+QWFlYxVN4+XPKrrImWUv6UraB9e0LoPrH7d/OeZeDXwFgen0LfjUmkakHF/3150tbrxG/E2upJ7nLQnh63ozE3LwEng6bWxB8VI5h4SbDQEijTq6cHHH9agDcdDrSSHMfDINeH9Pcj9sOdE52EjSgYd0DTGljMEhLTPMshGrXt/sB5mKR0/ydG9vg59AKsHwqU/RIgP8ru/3oZZj1Ur/Kmdzh1/agHbKuFF7s1iSeQ9QEKnjVRfP7j4flmswcVIGFTnI5mWHry6O45Ydw4K8oYRjX4j1fkqE7arBql9f5GMPqS/xw=
  - secure: R+N3WQzdMeyqEQGWLDJR+zmjBezqGBIqN/Q6ziQTXG1YO85cYgwhs7d76NiqWXvx5QFCaVb4GDxJDb5AEYHIXiWJK6jOrEF4YlXdwfHLILY86caNMkfSPpj2/8fltATeTmXrKLDDLFSxkvctI0lCvUc+W4zWvbDpf1yKYU/ULXWFxvI5bNENAXe55uX2RVVAMNjQ2EWfYkIqm/AeG+VE55110REHtDmkKPE3zxXQoJZz5VW3ipEASvfworkBBdZSZ2+TdeYOmbEbGkS4VXEDcfg+JJx2x7O+wDbEcKGYfIaWQkuPOCkHoSvgaJKfJPOT4fmboROlY0bL4htSguv4LcyfDVyhSBpuKg8zd/k4BvAuWfbpp16z9e8yUcntKCc9mKhqXU7swpzylkgsfZtQm2YABRN81EDkHFtQfLk24ndpufOlzmvCEp/83Nlg8Rxkw4x8sGp0aMLcVoO4mCEGjZ2KlctV6MZf7Y0hIc3v945vzU5oPn0K9icTSzVR1yCBCtkgL9UeATNXF5vYxUJThvfH3TmH5Bv6RN2MnmFBcGBXuISzrV6F84Koq6/pwKlVHyyI1YRHeUXdEuj0fY9eXBlcuBH1q+nTAndXZ8Iw/Wh1Gbib5SMs8NIsdB+3l8D99mfH/ACWJP7aM6hV5ZEcwmpDqFJSbZIv1QSEWZwzypM=
