language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
addons:
  apt:
    update: true
    packages:
    - unixodbc
    - odbcinst
    - unixodbc-dev
    - libz-dev
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: "[PYPI_API_KEY]"
  on:
    tags: true
    repo: soundstripe/iaccess
    python: 3.8
env:
  global:
  - IACCESS_HOST=pub400.com
  - secure: qeE4xPAAfdnTO0p3Ze2mKgZiZNEtVOB9jiwJ2Oi1uAnBPktzZHY/SjIFQ2yGJlDiuZOf8OmeARyXx+9yHn04/+LJ1zDlGDVmPGk1IcJyvnInGQ1+Vb4POq68tbSlmtBDT2rsStkSP8tIDV4gbg6V5PT4CO8HeyZhapHzsdgVLEG/mymtfHAjTYWlInvgBe7ktOFVsffBpmfFOl/Rz6ta1sPWT6RuUmgFG8Po6ntzO3Rl2oiEGaRQZtiY1xh42xZ5BxWLpUhuIX0g6YmVuTP+FK91R9n+iR9mktNVt9ZCI35Tjw7/Iq3HMwWg5WLzSV+qB90ekH/6qe1xKihHRJrl0XZS0Z2fkoaHgG6HqUBJxFuKCZyGeq4bXqiSQsRFm4V8+osEEudFaq9U9KYn1OrRC7wVbZw+OFJemojEAoK/UfQm9Q0Mab+2PdJT23W45Qc4D5B06gvjdxWdQFOXCR96rCQRDZKA7X1Vz3LFfYGHcKTc0RCqsGOUEx2f6ej9g2Lu6ZhnYdhWzekgb4ZTWTt8BPiQGyHKxGIvTyOCFCjaZPJR9vKlvYs9llffXgbr7y7VLSf9fvVRqA1LvIfho8eJX2IehPyrHMRSTyvnjXaCvQ/0LhXQnfyb+DSxHBxPPYgdFEVcmvUpJC3OI+/nYcdXvYJAOiEPXrLjaNt6i67zLao=
  - secure: G8LhNVUmvrYwoWXESlFSwRkyJRU5b8VWFr/GGUApA7R6yof2knymINyOwBgNqnlgrCUnzcpi0SjqgIVYlR0tfhkia372OBE+LLOntYC93b2/1+cdos5EqQ+cUNGxwfbTBIMQ10M+BiVK+Reuo6IZ8iQ8FusMewNIRgcbY1VJMCNZm6m1FhKKds0Pw9zHS2Ue8dHgMSPlwRMEE0tAn07cdBhv1yi4mmMBnq9tGsdWtmvGqPnqolz7cF6c5vYmvIURCjsLM2F2WAcRxJI3+nV9zL04/YZM4KOUdokN5RUu8fp3OIWY+ABxWrne2nln/L4MEejkiGoJy5u3wD1apZ0U+9SUSdjFYbUibiYK25d5/9JjkgG1cSs2hOqZCJiZTBznrSlKnqKNOAj1lrVxOOs0l40rRNAnZrvQqPiMBFgeqk5Wp1qIT9S/geiqttY4kRpIdVZksScYdoHKG4fyMGSPPdRSJqIvXdaIVt4Xnx9byf5vkOFsWTz1TWKt6GSf20G5hyDDd7cgCNyc6Yk/zrIhgyKg2B5aNqO+MTGs3DWbNsZSH+FuBj0A0BLb1lfRMp30FYRenR5cVP+XGTLgg7KQJaC/Ly8k2/80KBCBUIR39M9B34y9bs25nDTniUW1L7pNwHL2oWol4/Gpuj495S7Lzip0B92xEoEWtxzE7bPnmdg=
  - secure: M73BITNSPWcpeiGy60e+Kip0f8/LDgiemArDUmbUtKCbOshrYZrtYwskg2VHjNMneNbjV2uAb8OP9lppWqGmCH4DNiZIySQVI6K5B8fvS0ghNGb8zSWEgRf/14ee3MWXfX1v+os5jgLz+Q78K2U3ybMp+7QfdM6xv4qXH7dPlhnaPffPqxUqYRrEIl4uK3XzNRrDCZ1UlTfbJ8VNGAHlND5tmZKOwdGkWLXnGNtuvF+kcx9UzfEZj/gKHp3Llng09zLGoxNaJ/BzphdmsQVL3gy7WSJVnb15XVtl6acYwBCdL7MzKbs73fMY9MLmecFqOjkrX7FZN5qTzoSU2D1UQCQ8/YG7j/yvMQudSuHrlS/EoQzuo8UWm2DBKcZlvyEXsXR/Yo/r/sqRQWKyQYVN4erTM/dm6ESOy38JekE0NkJCN/+KWL0LeYUiE8nPwk/ODAgUkB8KxyuCAxL0hsCJCcSwnxoTo+/7JFkpANXkeTIhDlm91hhWMua634gO7zmYMycHKs+UeX1Lr3EE0GRGm8uzfGoVSSPM5YJVRxhQbe2jg6pUQj4j35eXBSQmXH7ig5TErTrf7uln68GepXI/5+gf6K+L3fIHPioxTnb8xcToLIdHNLJ+Tr7mZz0HVThPtcuaB+f5kJ+wTzxhmo5AtGmlvj0kUi7JCaW16xmfqJE=
  - secure: HwpaHfVitUUwzXOLE2Uif/1vGgfw7Ys2fMQnOUAYzLfL8hC64BV9fIvbRYXUXEhDZTySbgBYoUY9yWpDOw/zS6yB2Cxjd9+7t7OTxNvdQENBD2tYUBUhi14A35YqZz/9QPMhTtbfCm6k39syjC85HfRJ1LfM1xcK8WJWyXgz2Y1ijj2cgmX8FLyXoz1Evz5nih38M6ZokM8qi4euPYcylK4N9K2vAc0Q1K6u8Wxp3IGlaZWN87k1n7Wbvdi195qLxg4besty5Dhro2392ExI6vVHgaXZbnDpRSttYPt5QsVyyD9sZryBO2cTyZgrCvQj+5Sa6JehBAO736j5pZhbBrFKyQegso1v2CH1EWFy2DaNUi0Nvd7gBUadI+QWFlYxVN4+XPKrrImWUv6UraB9e0LoPrH7d/OeZeDXwFgen0LfjUmkakHF/3150tbrxG/E2upJ7nLQnh63ozE3LwEng6bWxB8VI5h4SbDQEijTq6cHHH9agDcdDrSSHMfDINeH9Pcj9sOdE52EjSgYd0DTGljMEhLTPMshGrXt/sB5mKR0/ydG9vg59AKsHwqU/RIgP8ru/3oZZj1Ur/Kmdzh1/agHbKuFF7s1iSeQ9QEKnjVRfP7j4flmswcVIGFTnI5mWHry6O45Ydw4K8oYRjX4j1fkqE7arBql9f5GMPqS/xw=
